package com.aibyd.apps.db.dao;

import com.aibyd.apps.db.domain.MallRegion;
import com.aibyd.apps.db.domain.MallRegionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MallRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_region
     *
     * @mbg.generated
     */
    long countByExample(MallRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_region
     *
     * @mbg.generated
     */
    int deleteByExample(MallRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_region
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_region
     *
     * @mbg.generated
     */
    int insert(MallRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_region
     *
     * @mbg.generated
     */
    int insertSelective(MallRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallRegion selectOneByExample(MallRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallRegion selectOneByExampleSelective(@Param("example") MallRegionExample example, @Param("selective") MallRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<MallRegion> selectByExampleSelective(@Param("example") MallRegionExample example, @Param("selective") MallRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_region
     *
     * @mbg.generated
     */
    List<MallRegion> selectByExample(MallRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallRegion selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MallRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_region
     *
     * @mbg.generated
     */
    MallRegion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_region
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MallRegion record, @Param("example") MallRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_region
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MallRegion record, @Param("example") MallRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MallRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MallRegion record);
}