package com.aibyd.apps.db.dao;

import com.aibyd.apps.db.domain.MallCouponUser;
import com.aibyd.apps.db.domain.MallCouponUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MallCouponUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    long countByExample(MallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    int deleteByExample(MallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    int insert(MallCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    int insertSelective(MallCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallCouponUser selectOneByExample(MallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallCouponUser selectOneByExampleSelective(@Param("example") MallCouponUserExample example, @Param("selective") MallCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<MallCouponUser> selectByExampleSelective(@Param("example") MallCouponUserExample example, @Param("selective") MallCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    List<MallCouponUser> selectByExample(MallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallCouponUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MallCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    MallCouponUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallCouponUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MallCouponUser record, @Param("example") MallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MallCouponUser record, @Param("example") MallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MallCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MallCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") MallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}