package com.aibyd.apps.db.dao;

import com.aibyd.apps.db.domain.MallAddress;
import com.aibyd.apps.db.domain.MallAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MallAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     */
    long countByExample(MallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     */
    int deleteByExample(MallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     */
    int insert(MallAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     */
    int insertSelective(MallAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallAddress selectOneByExample(MallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallAddress selectOneByExampleSelective(@Param("example") MallAddressExample example, @Param("selective") MallAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<MallAddress> selectByExampleSelective(@Param("example") MallAddressExample example, @Param("selective") MallAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     */
    List<MallAddress> selectByExample(MallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallAddress selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MallAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     */
    MallAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallAddress selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MallAddress record, @Param("example") MallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MallAddress record, @Param("example") MallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MallAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MallAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") MallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}