package com.aibyd.apps.db.dao;

import com.aibyd.apps.db.domain.MallOrderGoods;
import com.aibyd.apps.db.domain.MallOrderGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MallOrderGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     */
    long countByExample(MallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     */
    int deleteByExample(MallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     */
    int insert(MallOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     */
    int insertSelective(MallOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallOrderGoods selectOneByExample(MallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallOrderGoods selectOneByExampleSelective(@Param("example") MallOrderGoodsExample example, @Param("selective") MallOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<MallOrderGoods> selectByExampleSelective(@Param("example") MallOrderGoodsExample example, @Param("selective") MallOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     */
    List<MallOrderGoods> selectByExample(MallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallOrderGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MallOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     */
    MallOrderGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MallOrderGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MallOrderGoods record, @Param("example") MallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MallOrderGoods record, @Param("example") MallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MallOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MallOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") MallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}